import { useEffect, useState } from "react"
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Geist, Geist_Mono } from "next/font/google"
import { Table } from "@mantine/core"
import { Data } from "../../util/types"
import { displayDate } from "../../util/functions"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

function RawTable(props: { entries: Data }) {
	const { entries } = props
	const rows = entries.map((element, index) => {
		return (
			<Table.Tr key={index}>
				<Table.Td>{element.project.name}</Table.Td>
				<Table.Td>{element.employee.name}</Table.Td>
				<Table.Td>{displayDate(element.date)}</Table.Td>
				<Table.Td>{element.hours}</Table.Td>
			</Table.Tr>
		)
	})

	return (
		<Table stickyHeader withRowBorders striped>
			<Table.Thead>
				<Table.Tr>
					<Table.Th>Project</Table.Th>
					<Table.Th>Employee</Table.Th>
					<Table.Th>Date</Table.Th>
					<Table.Th>Hours</Table.Th>
				</Table.Tr>
			</Table.Thead>
			<Table.Tbody>{rows}</Table.Tbody>
		</Table>
	)
}

export default function Home() {
	const [data, setData] = useState<Data>()

	useEffect(() => {
		const fetchData = async (projects: number, employees: number, entries: number) => {
			const res = await fetch(
				`/api/mockData?projects=${projects}&employees=${employees}&entries=${entries}`
			)
			const data = await res.json()
			setData(data)
		}

		fetchData(3, 5, 30)
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
				{data && <RawTable entries={data} />}
			</div>
		</>
	)
}
