import { useEffect } from "react"
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Geist, Geist_Mono } from "next/font/google"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export default function Home() {
	useEffect(() => {
		const fetchData = async (projects: number, employees: number, entries: number) => {
			const res = await fetch(
				`/api/mockData?projects=${projects}&employees=${employees}&entries=${entries}`
			)
			const data = await res.json()
			console.log(data)
		}

		fetchData(3, 5, 20)
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}></div>
		</>
	)
}
